### ISSUE TITLE
Add new keyword : Then response body should not have path

### ISSUE THREAD

**Issue by jmagaru** [ariesb/autokin#3]
Just a minor issue. Adding validation when the json response has been updated and deleted some object items.
Example: Json response should not have contained this json query

$[0].data.cart_data.sellers[?(@.items[0].item_id == 3560)].items[0].item_id

Where item object id 3560 has been deleted.

**Comment by ariesb** [comment]
@jmagaru This will be added on 1.7.2 upcoming version.
